import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Fragment } from "react";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Ancon Digital SA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Catamaran:wght@900&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <nav> */}
      {/* <div className="bar"> */}
      {/* <div className="nav-item username">Ancon Digital</div> */}
      {/* <div className="nav-item nav-link"> */}
      {/* <details> */}
      {/* <summary> */}
      {/* <a href="#quienessomos"> &#128076; Quienes somos? </a> */}
      {/* </summary> */}
      {/* </details> */}
      {/* </div> */}
      {/* <div className="nav-item nav-link"> */}
      {/* <details> */}
      {/* <summary> */}
      {/* <a href="#servicios"> &#128161; Servicios</a> */}
      {/* </summary> */}
      {/* </details> */}
      {/* </div> */}
      {/* <div className="nav-item nav-link"> */}
      {/* <details> */}
      {/* <summary> */}
      {/* <a href="#portafolio"> &#128203; Portafolio</a> */}
      {/* </summary> */}
      {/* </details> */}
      {/* </div> */}
      {/* <div className="nav-item nav-link"> */}
      {/* <details> */}
      {/* <summary> */}
      {/* <a href="#c/ontacto"> &#128231; Contáctanos</a> */}
      {/* </summary> */}
      {/* </details> */}
      {/* </div> */}
      {/* </div> */}
      {/* </nav> */}

      <header className="flex flex-wrap flex-row justify-between md:items-center md:space-x-4 bg-white py-6 px-6 relative">
        <a href="#" className="block">
          <span className="sr-only">themes.dev</span>
          <img
            className="h-6 md:h-8"
            src="/grafico.png"
            alt="Themes.dev Logo"
            title="Themes.dev Logo"
          ></img>
        </a>
        <button className="inline-block md:hidden w-8 h-8 bg-gray-200 text-gray-600 p-1">
          <svg
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fillRule="evenodd"
              d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
              clipRule="evenodd"
            ></path>
          </svg>
        </button>
        <nav className="absolute md:relative top-16 left-0 md:top-0 z-20 flex flex-col md:flex-row md:space-x-6 font-semibold w-full md:w-auto bg-white shadow-md rounded-lg md:rounded-none md:shadow-none md:bg-transparent p-6 pt-0 md:p-0 ">
          <a href="#quienessomos" className="block py-1 text-indigo-600 hover:underline">
          Quienes somos?
          </a>
          <a href="#servicios" className="block py-1 text-gray-600 hover:underline">
            Servicios
          </a>
          <a href="#portafolio" className="block py-1 text-gray-600 hover:underline">
          Portafolio
          </a>
          <a href="#contacto" className="block py-1 text-gray-600 hover:underline">
            Contacto
          </a>
        </nav>
      </header>

      <main>
        {/* <!-- titulo-central --> */}
        <div className="grid justify-items-center">
          <div className="titlePage m-8 max-w-lg bg-indigo-200">
            <div className="text-3xl">
              <h1>Digitaliza tu negocio Avanza</h1>
            </div>
            <div className="text-2xl">
              <h1> despega y evoluciona!</h1>
            </div>
          </div>
          <div className="my-12 w-4/5">
            {/* <iframe
              width="99%"
              height="315px"
              src="https://www.youtube.com/embed/aJzQDpzC828"
              title="YouTube video player"
              frameBorder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen
            ></iframe> */}
          </div>
          <div className="w-4/5 mb-10">
            <h2 className="text-indigo-400" id="quienessomos">
              Quienes somos?
            </h2>
            <p className="Hero">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eaque
              nostrum illo fuga corrupti repudiandae ipsam, enim officia sint
              excepturi aperiam maiores? Aperiam unde ad temporibus cupiditate
              aliquid, eaque quis quibusdam? Lorem ipsum dolor sit amet
              consectetur, adipisicing elit. Eaque nostrum illo fuga corrupti
              repudiandae ipsam, enim officia sint excepturi aperiam maiores?
              Aperiam unde ad temporibus cupiditate aliquid, eaque quis
              quibusdam? Lorem ipsum dolor sit amet consectetur, adipisicing
              elit. Eaque nostrum illo fuga corrupti repudiandae ipsam, enim
            </p>
          </div>

          <div>
            <h2 className="text-indigo-400">Servicios disponibles</h2>
            <h4>
              Desarrollos a la medida, soluciones basadas en previos estudios de
              las necesidades reales
            </h4>
          </div>
          <div className="grid sm:grid-cols-1 md:grid-cols-3 m-5 text-indigo-500">
            <div className="w-11/12 grid justify-items-center shadow-lg p-8 rounded-lg">
              <h2 className="text-indigo-400">Desarrollo web</h2>
              <img
                className="border-0"
                src="/Create-rafiki.png"
                alt="servicio de diseño web Illustration by Freepik Storyset"
                title=" servicio de diseño web"
              ></img>
              <p>Apps y websites</p>
            </div>
            <div className="w-11/12 grid justify-items-center shadow-lg p-8 rounded-lg">
              <h2 className="text-indigo-400">Diseño gráfico</h2>
              <img
                className="border-0"
                src="/Create-amico.png"
                alt="servicio de diseño web Illustration by Freepik Storyset"
                title=" servicio de diseño web"
              ></img>
              <p>Identidad de marca</p>
            </div>
            <div className="w-11/12 grid justify-items-center shadow-lg p-8 rounded-lg">
              <h2 className="text-indigo-400">Marketing digital</h2>
              <img
                className="border-0"
                src="/Launching-rafiki.png"
                alt="servicio de diseño web Illustration by Freepik Storyset"
                title=" servicio de diseño web"
              ></img>
              <p>Estrategia y pauta</p>
            </div>
          </div>
          <p>
            <strong> DISEÑO WEB : </strong> Lorem ipsum dolor sit, am aperiam
            voluptate laboriosam harum.
            <strong> DISEÑO GRAFICO : </strong> Lorem ipsum dolor, repudiandae
            facere iste eligendi, eos nisir nisi excepturi!
            <strong> MARKETING DIGITAL: </strong> Lorem ipsum dolor sit amet
            consectetur, a vel doloremque.
            <strong>
              Cerca del 90% de los comercios en el mundo funcionan con
              componentes digitales.
            </strong>
          </p>

          <h1 className="text-indigo-400" id="portafolio">
            Últimos proyectos realizados
          </h1>

          <div className="grid md:grid-cols-3 sm:grid-cols-1 m-5 text-indigo-500">
            <div className="w-11/12 grid justify-items-center shadow-lg p-8 rounded-lg">
              <p>
                <img
                  className="border-0"
                  src="/cliente4.png"
                  alt="servicio de diseño web"
                  title=" servicio de diseño web"
                ></img>
                <strong id="ELEMENTO"> Titulo:</strong>
                Lorem ipsum dolor sit, am aperiam voluptate laboriosam harum
                <a href="https://aplacitos.com" target="_blank">
                  <button className="button-card bg-indigo-400 rounded-full">
                    Ver más &#128270;
                  </button>
                </a>
              </p>
            </div>
            <div className="w-11/12 grid justify-items-center shadow-lg p-8 rounded-lg">
              <p>
                <img
                  className="border-0"
                  src="/cliente1.png"
                  alt="servicio de diseño web"
                  title=" servicio de diseño web"
                ></img>
                <strong id="ELEMENTO"> Titulo:</strong>
                Lorem ipsum dolor sit, am aperiam voluptate laboriosam harum
                <a href="https://dannyduranmusic.com" target="_blank">
                  <button className="button-card bg-indigo-400 rounded-full">
                    Ver más &#128270;
                  </button>
                </a>
              </p>
            </div>
            <div className="w-11/12 grid justify-items-center shadow-lg p-8 rounded-lg">
              <p>
                <img
                  className="border-0"
                  src="/cliente3.png"
                  alt="servicio de diseño web"
                  title=" servicio de diseño web"
                ></img>
                <strong id="ELEMENTO"> prueba:</strong>
                Lorem ipsum dolor sit, am aperiam voluptate laboriosam harum
                <a
                  href="https://www.laagenciainmobiliaria.com/"
                  target="_blank"
                >
                  <button className="button-card bg-indigo-400 rounded-full">
                    Ver más &#128270;
                  </button>
                </a>
              </p>
            </div>
            <div className="w-11/12 grid justify-items-center shadow-lg p-8 rounded-lg">
              <p>
                <img
                  className="border-0"
                  src="/cliente2.png"
                  alt="portafolio"
                  title=" portafolio"
                ></img>
                <strong id="ELEMENTO"> prueba:</strong>
                Lorem ipsum dolor sit, am aperiam voluptate laboriosam harum
                <a>
                  <button className="button-card bg-indigo-400 rounded-full">
                    Ver más &#128272;
                  </button>
                </a>
              </p>
            </div>
            <div className="w-11/12 grid justify-items-center shadow-lg p-8 rounded-lg">
              <p>
                <img
                  className="border-0"
                  src="/cliente5.png"
                  alt="portafolio"
                  title=" portafolio"
                ></img>
                <strong id="ELEMENTO"> prueba:</strong>
                Lorem ipsum dolor sit, am aperiam voluptate laboriosam harum
                <a>
                  <button className="button-card bg-indigo-400 rounded-full">
                    Ver más &#128272;
                  </button>
                </a>
              </p>
            </div>

            <div className="w-11/12 grid justify-items-center shadow-lg p-8 rounded-lg">
              <p>
                <img
                  className="border-0"
                  src="/cliente6.png"
                  alt="portafolio"
                  title=" portafolio"
                ></img>
                <strong id="ELEMENTO"> prueba:</strong>
                Lorem ipsum dolor sit, am aperiam voluptate laboriosam harum
                <a>
                  <button className="button-card bg-indigo-400 rounded-full">
                    Ver más &#128272;
                  </button>
                </a>
              </p>
            </div>
          </div>
          {/* <!-- boton de whatsapp --> */}
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non
            inventore quas delectus excepturi iusto? Fugit vel error illo
            maiores, possimus illum tenetur consectetur rerum veniam ipsum
            facilis impedit? Necessitatibus, soluta.
          </p>
          <a href="https://api.whatsapp.com/send?phone=50766937639&text=Hola,%20he%20visto%20su%20numero%20en%20el%20enlace%20de%20ancon%20digital%20sa%20">
            <button className="rounded-full bg-green-400 p-3 m-12">
              &nbsp; Haz clic aquí, hablemos!&nbsp; &#9995;
            </button>
          </a>
        </div>
      </main>

      <footer className="bg-indigo-900" id="contacto">
        <div className="grid grid-col-3 text-center">
          <div>
            <a href="https://api.whatsapp.com/send?phone=50766937639&text=Hola,%20he%20visto%20su%20numero%20en%20el%20enlace%20de%20ancon%20digital%20sa%20">
              contacto{" "}
            </a>
          </div>
          <div>
            <a href="mailto:info@ancondigitalsa.com">
              {" "}
              &#128231; info@aquivaelcorreo.com‎{" "}
            </a>
          </div>
          <div className="copy-right">
            Desarrollado por Ancon Digital SA © Copyright 2021
          </div>
        </div>
      </footer>
    </Fragment>
  );
}
